In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\Shree\\Downloads\\lp_3_datasets\\emails.csv")
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [3]:
df = df.dropna()   #removing rows having missing data
df = df.drop(columns = ["Email No."])

In [4]:
x = df.drop(columns = ["Prediction"])
y = df["Prediction"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier()
knc.fit(x_train, y_train)
y_pred_knc = knc.predict(x_test)
y_pred_knc

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [6]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)
y_pred_svc = svc.predict(x_test)
y_pred_svc

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [8]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("accuracy in prediction using knc: ", accuracy_score(y_test, y_pred_knc))
print("confusion matrix for knc: \n", confusion_matrix(y_test, y_pred_knc))

print("error in prediction using svm: ", accuracy_score(y_test, y_pred_svc))
print("confusion matrix for knc: \n", confusion_matrix(y_test, y_pred_svc))

accuracy in prediction using knc:  0.851159793814433
confusion matrix for knc: 
 [[980 154]
 [ 77 341]]
error in prediction using svm:  0.8009020618556701
confusion matrix for knc: 
 [[1087   47]
 [ 262  156]]
